#!/bin/bash
#SBATCH --job-name=MERGE_CHUNKS
#SBATCH --account=p697_norment
#SBATCH --time=48:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=8000M
#SBATCH --cpus-per-task=1
#SBATCH --array=1-8
source /cluster/bin/jobsetup
# If you have other way of running PLINK2 and python software feel free to replace the set of commands below
module load singularity/3.7.1
module load Java/11.0.2
module load BCFtools/1.9-foss-2018b
export COMORMENT=/ess/p697/data/durable/s3-api/github/comorment
export SINGULARITY_BIND=""$COMORMENT/containers/reference:/REF:ro,/cluster/projects/p697:/cluster/projects/p697""
export SIF=$COMORMENT/containers/singularity
export PLINK="singularity exec --home $PWD:/home $SIF/gwas.sif plink"
export PLINK2="singularity exec --home $PWD:/home $SIF/gwas.sif plink2"
export PYTHON="singularity exec --home $PWD:/home $SIF/python3.sif python"
export MINIMAC4="singularity exec --home $PWD:/home /cluster/projects/p697/github/comorment/containers/singularity/gwas.sif minimac4"
export BEAGLE_CONFORM_GT=/cluster/projects/p697/projects/moba_qc_imputation/software/beagle_download/conform-gt.24May16.cee.jar
export BEAGLE=/cluster/projects/p697/projects/moba_qc_imputation/software/beagle_download/beagle.28Jun21.220.jar
export HRC=/cluster/projects/p697/projects/moba_qc_imputation/resources/HRC
export impute5=/cluster/projects/p697/projects/moba_qc_imputation/software/impute5_1.1.5_static
export hrc_prefix=_egaz00001239288_hrc.r1-1.ega.grch37.chr21.haplotypes
export QCTOOL="singularity exec -B $PWD:$PWD /ess/p697/data/durable/projects/moba_qc_imputation/software/qctool_v2.2.0.sif qctool"
set -o errexit


chunk_files=$(ls chr24.impute2.ichunk*.chunk${SLURM_ARRAY_TASK_ID})


cat chr24.impute2.ichunk00.chunk${SLURM_ARRAY_TASK_ID} | cut -d ' ' -f 1-5 | $PYTHON rename_multiallelic_snps.py 24 > chr24.impute2.chunk${SLURM_ARRAY_TASK_ID}.renamed_snps


paste_command="paste <(cat chr24.impute2.chunk${SLURM_ARRAY_TASK_ID}.renamed_snps)"
for chunk_file in $chunk_files;
do
  paste_command+=" <(cut -d ' ' -f 6- <(cat $chunk_file))"
done

eval "$paste_command | sed 's/\t/ /g' | gzip > chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.gen.gz"


> chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}_samples
for chunk_file in $chunk_files;
do
  sample_file="${chunk_file%.*}.chunk${SLURM_ARRAY_TASK_ID}_samples"
  tail -n +3 $sample_file >> chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}_samples
done

echo "ID_1 ID_2 missing sex plink_pheno" > chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.samples
echo "0 0 0 D B" >> chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.samples

awk '{print $2, $1, $3, $4, $5}' chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}_samples >> chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.samples

$QCTOOL -g chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.gen.gz -s chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.samples -infer-ploidy-from sex -assume-chromosome Y -snp-stats -osnp chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.snp.stats
$QCTOOL -g chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.gen.gz -s chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.samples -og  chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.bgen -os chr24.imputed.chunk${SLURM_ARRAY_TASK_ID}.sample


